version: '3.7'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=c137
      - POSTGRES_DATABASEjob_api
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"
    volumes:
      - /app/docker:/var/lib/postgresql/data
    networks:
      - api
  job-api:
    image: job-backend:developer
    container_name: job-api-dev
    restart: always
    command: yarn dev
    working_dir: /app
    ports: 
      - 3333:3333
    environment:
      - NODE_ENV=docker-developer
    depends_on:
      - db
    networks:
      - api
networks:
  api:
    driver: bridge