version: '3.7'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=c137
    ports:
      - "5432:5432"
    volumes:
      - ./.docker:/var/lib/postgresql/data